name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - aom==3.6.0
  - blas==1.0
  - brotli-python==1.0.9
  - bzip2==1.0.8
  - ca-certificates==2025.2.25
  - cairo==1.16.0
  - certifi==2025.1.31
  - charset-normalizer==3.3.2
  - dav1d==1.2.1
  - expat==2.6.4
  - ffmpeg==6.1.1
  - filelock==3.13.1
  - fontconfig==2.14.1
  - freetype==2.12.1
  - fribidi==1.0.10
  - gdk-pixbuf==2.42.10
  - gettext==0.21.0
  - giflib==5.2.2
  - glib==2.78.4
  - glib-tools==2.78.4
  - gmp==6.3.0
  - gmpy2==2.2.1
  - graphite2==1.3.14
  - harfbuzz==10.2.0
  - icu==73.1
  - idna==3.7
  - jinja2==3.1.5
  - jpeg==9e
  - lame==3.100
  - lcms2==2.16
  - leptonica==1.82.0
  - lerc==4.0.0
  - libarchive==3.7.7
  - libcxx==14.0.6
  - libdeflate==1.22
  - libffi==3.4.4
  - libgfortran==5.0.0
  - libgfortran5==11.3.0
  - libglib==2.78.4
  - libiconv==1.16
  - libogg==1.3.5
  - libopenblas==0.3.21
  - libopus==1.3.1
  - libpng==1.6.39
  - librsvg==2.56.3
  - libtheora==1.1.1
  - libtiff==4.5.1
  - libvorbis==1.3.7
  - libvpx==1.13.1
  - libwebp==1.3.2
  - libwebp-base==1.3.2
  - libxml2==2.13.5
  - llvm-openmp==14.0.6
  - lz4-c==1.9.4
  - mpc==1.3.1
  - mpfr==4.2.1
  - mpmath==1.3.0
  - ncurses==6.4
  - networkx==3.4.2
  - openh264==2.1.1
  - openjpeg==2.5.2
  - openssl==3.0.16
  - pango==1.50.7
  - pcre2==10.42
  - pip==25.0
  - pixman==0.40.0
  - pysocks==1.7.1
  - pytorch==2.0.1
  - readline==8.2
  - requests==2.32.3
  - setuptools==75.8.0
  - sqlite==3.45.3
  - sympy==1.13.3
  - tesseract==5.2.0
  - tk==8.6.14
  - torchaudio==2.0.2
  - torchvision==0.15.2
  - typing_extensions==4.12.2
  - urllib3==2.3.0
  - wheel==0.45.1
  - xz==5.6.4
  - zlib==1.2.13
  - zstd==1.5.6
  - pip
  - pip:
    - accelerate==0.32.1
    - aiofiles==23.2.1
    - altair==5.5.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.8.0
    - attrs==25.1.0
    - Brotli==1.0.9
    - certifi==2025.1.31
    - charset-normalizer==3.3.2
    - click==8.1.8
    - contourpy==1.3.1
    - cycler==0.12.1
    - diffusers==0.25.0
    - exceptiongroup==1.2.2
    - fastapi==0.110.0
    - ffmpy==0.5.0
    - filelock==3.13.1
    - fonttools==4.56.0
    - fsspec==2025.2.0
    - gmpy2==2.2.1
    - gradio==4.44.1
    - gradio_client==1.3.0
    - groovy==0.1.2
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.27.0
    - huggingface-hub==0.25.2
    - idna==3.7
    - importlib_metadata==8.6.1
    - importlib_resources==6.5.2
    - inquirerpy==0.3.4
    - Jinja2==3.1.5
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - kiwisolver==1.4.8
    - markdown-it-py==3.0.0
    - MarkupSafe==2.1.5
    - matplotlib==3.10.1
    - mdurl==0.1.2
    - mpmath==1.3.0
    - mypy-extensions==1.0.0
    - narwhals==1.29.1
    - networkx==3.4.2
    - numpy==1.26.4
    - omegaconf==2.3.0
    - orjson==3.10.15
    - packaging==24.2
    - pandas==2.2.3
    - peft==0.13.2
    - pfzy==0.3.4
    - pillow==10.4.0
    - pip==25.0
    - prompt_toolkit==3.0.50
    - psutil==5.9.8
    - pydantic==2.6.1
    - pydantic_core==2.16.2
    - pydub==0.25.1
    - Pygments==2.19.1
    - pyparsing==3.2.1
    - pyre-extensions==0.0.29
    - PySocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-multipart==0.0.20
    - pytz==2025.1
    - PyYAML==6.0.2
    - referencing==0.36.2
    - regex==2024.11.6
    - requests==2.32.3
    - rich==13.9.4
    - rpds-py==0.23.1
    - ruff==0.9.9
    - safehttpx==0.1.6
    - safetensors==0.4.0
    - semantic-version==2.10.0
    - setuptools==75.8.0
    - shellingham==1.5.4
    - six==1.17.0
    - sniffio==1.3.1
    - spaces==0.19.4
    - starlette==0.36.3
    - sympy==1.13.3
    - tokenizers==0.15.2
    - tomlkit==0.12.0
    - torch==2.0.1
    - torchaudio==2.0.2
    - torchvision==0.15.2
    - tqdm==4.67.1
    - transformers==4.36.2
    - typer==0.15.2
    - typing-inspect==0.9.0
    - typing_extensions==4.12.2
    - tzdata==2025.1
    - urllib3==2.3.0
    - uvicorn==0.34.0
    - wcwidth==0.2.13
    - websockets==11.0.3
    - wheel==0.45.1
    - xformers==0.0.20
    - zipp==3.21.0
